#!/bin/bash

# Run with CRON Job 0 0 3 * *

ipmitool -I lanplus -H 192.168.20.20 -U root -P calvin raw 0x30 0x30 0x01 0x00

#Dell Fans at 1800rpm
ipmitool -I lanplus -H 192.168.20.20 -U root -P calvin raw 0x30 0x30 0x02 0xff 0x06 
